### ISSUE TITLE
Authentication required when running Github action

### ISSUE THREAD

**Issue by GustavoGomezNS** [wpengine/github-action-wpe-site-deploy#100]
**Describe the bug**
I get an error whenever running the WPE Site deploy action

### To reproduce
Try to deploy to WPE using this GH action

### Expected behavior
Github action pulls the image from the repo

### Build Output & Screenshots
``` 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"wpengine/site-deploy","Action":"pull"}]}]}
```

![image](https://github.com/user-attachments/assets/6066c279-058d-4a5d-8440-2b545f699095)

**Comment by apmatthews** [comment]
Hi @GustavoGomezNS, thanks for raising! This action uses an image hosted on Docker Hub, which is currently experiencing an incident. It looks like they have a fix, so hopefully things clear up soon.

https://www.dockerstatus.com/

**Comment by GustavoGomezNS** [comment]
Thanks for the quick reply! I figured as much... I'll wait for it to stabilize. Thanks for the support! Fell free to close the issue.
