### ISSUE TITLE
Sends entire repository, not just files that have changes

### ISSUE THREAD

**Issue by WPAcademic** [wpengine/github-action-wpe-site-deploy#33]
**Describe the bug**
Outside of what you tell it to ignore with exclude and exclude-from options, this doesn't take into consideration that not all files need to be sent from the repo to WP Engine. It sends the entirety of the repository rather than just the files that have differences between the sources and destination.

### To reproduce
Use the sample .yml file as provided

### Expected behavior
Only the files with differences should be excluded.

### Version information
- Action version: v3.1.1
- WordPress version: 6.0

**Comment by daniel-savo** [comment]
Hi @WPAcademic,

This is a known limitation of the current implementation, due to how change detection happens in rsync and the GitHub Actions environment. We're planning on looking into ways to avoid this in the future, so keep an eye out for future updates!

**Comment by WPAcademic** [comment]
> Hi @WPAcademic,
> 
> This is a known limitation of the current implementation, due to how change detection happens in rsync and the GitHub Actions environment. We're planning on looking into ways to avoid this in the future, so keep an eye out for future updates!

Thanks for clarifying. I thought my implementation was "off". Still, thanks for the wonderful implementation (especially the linting part). 

I'll stay tuned -- huge fan of this approach.
