### ISSUE TITLE
V3.2.3 breaks my workflows

### ISSUE THREAD

**Issue by vanderwijk** [wpengine/github-action-wpe-site-deploy#67]
**Describe the bug**
When running my workflow using v3 (which automatically uses the most recent v3 version of the wpe-site-deploy script) I am getting this error:

debug1: send_pubkey_test: no mutual signature algorithm
debug1: No more authentication methods to try.
wpe_gha+xxxx@xxxxx.ssh.wpengine.net: Permission denied (publickey).

### Version information
- Action version: 3.2.3

Reverting to v3.2.2 fixes this issue.

**Comment by landbryo** [comment]
I'm seeing the same issue after yesterday's release.

**Comment by alexanderzuniga** [comment]
Hi there, This is a security release to ensure the most secure key encryptions are supported. 
Replacing an RSA key with an ed25519 key should quickly resolve this error. 

Our setup guide in portal can help setup the right encryption. 
https://my.wpengine.com/profile/github_action

https://wpengine.com/support/troubleshooting-ssh-gateway-issues/#No_Mutual_Signature_Algorithm

If issues persist, please reach out to the WP Engine support team: https://my.wpengine.com/support

**Comment by yohdev-von** [comment]
This issue is also occurring for me. Even after replacing with an RSA key.

**Comment by sarahricker** [comment]
>  Even after replacing with an RSA key.

Hi @yohdev-von! We recommend using a **ed25519 key** 

To generate a new key in the recommended format, use `ssh-keygen -t ed25519 -f ~/.ssh/wpengine_ed25519`. 
Use the new key files `wpengine_ed25519` and `wpengine_ed25519.pub`

If issues persist, please reach out to the WP Engine support team: https://my.wpengine.com/support
