### ISSUE TITLE
Instructions unclear: Git push vs SSH Gateway

### ISSUE THREAD

**Issue by phillamb168** [wpengine/github-action-wpe-site-deploy#73]
I was banging my head against a wall trying to understand why I wasn't able to get my deploy job to function - I was receiving `Permission denied (publickey).` after every push. This was because I had set the public key in WPE via the 'Git Push' settings for each of the environments. If you're reading this: you MUST add the SSH pubkey via profile/ssh_keys in wpengine. 

I can submit a PR with a change for the README if y'all think it's warranted. 

For what it's worth - I am not a huge fan of this method because it means that the ability to execute a job is tied to a specific WPE account, as opposed to something project-specific.

**Comment by alexanderzuniga** [comment]
Thanks for the feedback! Correct, the SSH keys for GitHub Actions are different than the GitPush SSH keys. We are reviewing our instructions to help guide customers more effectively for a smoother setup.
