### ISSUE TITLE
Files not rsyncing to destination server.

### ISSUE THREAD

**Issue by jayhill90** [wpengine/github-action-wpe-site-deploy#79]
**Describe the bug**
When deploying to my staging install using the Github Action workflow, no new files or changed files get deployed.

### To reproduce
Push a commit to github on a branch named `staging` to trigger a workflow to deploy to a wpengine staging install..

YAML File
```
name: Deploy to WP Engine Staging Environment
on:
  push:
    branches:
     - staging
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
      - uses: actions/checkout@v3
      # Sets up node
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: gulp build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars 
        WPE_ENV: ${{secrets.STAGING_INSTALL}}
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        SCRIPT: "build.sh"
        CACHE_CLEAR: TRUE
        STG_ENV: ${{ secrets.STAGING_INSTALL}}
      env: 
        COMPOSER_AUTH: '{
          "http-basic": {
            "connect.advancedcustomfields.com": {
              "username":  ${{ secrets.ACF_KEY }},
              "password":  ${{ secrets.DOMAIN }} } } }'
        run: 'export COMPOSER_AUTH=${{ env.COMPOSER_AUTH }}'
```

### Expected behavior
If i make changes and commit them to  files within Github, then trigger a build and deploy, I then expect those changes to be deployed to my WP Engine installation including updates to composer.json files within the root of a site.

### Build Output & Screenshots

Deploy Job Logs

```
Deploying your code to:
***
setup ssh path
# ***.ssh.wpengine.net:22 SSH-2.0-Go
Begin PHP Linting.
PHP Lint Successful! No errors detected!
OpenSSH_9.3p2, OpenSSL 3.1.3 19 Sep 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ***.ssh.wpengine.net [34.28.156.84] port 22.
debug1: Connection established.
debug1: identity file /github/home/.ssh/wpe_id_rsa type 3
debug1: identity file /github/home/.ssh/wpe_id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.3
debug1: Remote protocol version 2.0, remote software version Go
debug1: compat_banner: no match: Go
debug1: Authenticating to ***.ssh.wpengine.net:22 as 'wpe_gha+***'
debug1: load_hostkeys: fopen /root/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:T8IoIgBRJ3gDjA6/q7i33+nSrrpVfZipYtxo1rqvww4
debug1: load_hostkeys: fopen /root/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
Warning: Permanently added '***.ssh.wpengine.net' (RSA) to the list of known hosts.
debug1: check_host_key: hostkey not known or explicitly trusted: disabling UpdateHostkeys
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /github/home/.ssh/wpe_id_rsa ED25519 SHA256:TP/LVZl4o/PGj3HlnsOHCf90byDbglaR7ksQHLbRdiI explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss>
debug1: kex_input_ext_info: ping@openssh.com (unrecognised)
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /github/home/.ssh/wpe_id_rsa ED25519 SHA256:TP/LVZl4o/PGj3HlnsOHCf90byDbglaR7ksQHLbRdiI explicit
debug1: Server accepts key: /github/home/.ssh/wpe_id_rsa ED25519 SHA256:TP/LVZl4o/PGj3HlnsOHCf90byDbglaR7ksQHLbRdiI explicit
Authenticated to ***.ssh.wpengine.net ([34.28.156.84]:22) using "publickey".
debug1: setting up multiplex master socket
debug1: channel 0: new mux listener [/github/home/.ssh/ctl/08de[18](https://github.com/shipstation/auctane-marketing-site/actions/runs/7007390824/job/19061610054#step:3:19)efbeb1d854d15ff587eae201bd4d1145a6] (inactive timeout: 0)
debug1: forking to background
debug1: Entering interactive session.
debug1: pledge: id
!!! MULTIPLEX SSH CONNECTION ESTABLISHED !!!
OpenSSH_9.3p2, OpenSSL 3.1.3 [19](https://github.com/shipstation/auctane-marketing-site/actions/runs/7007390824/job/19061610054#step:3:20) Sep [20](https://github.com/shipstation/auctane-marketing-site/actions/runs/7007390824/job/19061610054#step:3:21)23
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: multiplexing control connection
debug1: channel 1: new mux-control [mux-control] (inactive timeout: 0)
debug1: channel 2: new session [client-session] (inactive timeout: 0)
debug1: Sending command: rsync --server -vlogDtprze.iLsfxCIvu --inplace . sites/***/
debug1: mux_client_request_session: master session id: 2
sending incremental file list
./
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2

sent 45 bytes  received 19 bytes  2.33 bytes/sec
total size is 0  speedup is 0.00
OpenSSH_9.3p2, OpenSSL 3.1.3 19 Sep 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: multiplexing control connection
debug1: channel 1: new mux-control [mux-control] (inactive timeout: 0)
debug1: channel 2: new session [client-session] (inactive timeout: 0)
debug1: Sending command: test -s sites/***/build.sh
debug1: mux_client_request_session: master session id: 2
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
OpenSSH_9.3p2, OpenSSL 3.1.3 19 Sep 20[23](https://github.com/shipstation/auctane-marketing-site/actions/runs/7007390824/job/19061610054#step:3:24)
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: multiplexing control connection
debug1: channel 1: new mux-control [mux-control] (inactive timeout: 0)
debug1: channel 2: new session [client-session] (inactive timeout: 0)
debug1: Sending command: cd sites/*** && bash build.sh && wp --skip-plugins --skip-themes page-cache flush && wp --skip-plugins --skip-themes cdn-cache flush
debug1: mux_client_request_session: master session id: 2
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wpackagist-plugin/gravityforms-hubspot, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
```

The staging branch composer.json file does not have the `wpackagist-plugin/gravityforms-hubspot` entry in it anymore so should not be trying to install it when my build.sh script is ran on the WP Engine server. I had to manually add that build.sh file to the server to get this far because files have not been pushed up when running these workflows.

### Version information
- Action version: 3.2.4
- Git version: 2.39.3 (Apple Git-145)
- WordPress version: 6.2.2
- Operating system: OS X

### Additional context
Help me @alexanderzuniga, you're my only hope. 😂

**Comment by sanket9006** [comment]
Facing same issue

debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
Warning: Permanently added 'betterbladder1.ssh.wpengine.net' (RSA) to the list of known hosts.
debug1: check_host_key: hostkey not known or explicitly trusted: disabling UpdateHostkeys
debug1: rekey out after [42](https://github.com/Ideallivingcommerce/Better-Bladder/actions/runs/7033521518/job/19141864865#step:4:43)94967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /github/home/.ssh/wpe_id_rsa RSA SHA256:1HK9Nm3tvXAAE829mNP/uU1TDHH1Q/NdsMsnNzQgYYw explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss>
debug1: kex_input_ext_info: ping@openssh.com (unrecognised)
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /github/home/.ssh/wpe_id_rsa RSA SHA256:1HK9Nm3tvXAAE829mNP/uU1TDHH1Q/NdsMsnNzQgYYw explicit
debug1: Server accepts key: /github/home/.ssh/wpe_id_rsa RSA SHA256:1HK9Nm3tvXAAE829mNP/uU1TDHH1Q/NdsMsnNzQgYYw explicit
Authenticated to betterbladder1.ssh.wpengine.net ([20.112.[44](https://github.com/Ideallivingcommerce/Better-Bladder/actions/runs/7033521518/job/19141864865#step:4:45).254]:22) using "publickey".
debug1: setting up multiplex master socket
debug1: channel 0: new mux listener [/github/home/.ssh/ctl/b627cac767decd502bf53fdf22ea[45](https://github.com/Ideallivingcommerce/Better-Bladder/actions/runs/7033521518/job/19141864865#step:4:46)320a2[50](https://github.com/Ideallivingcommerce/Better-Bladder/actions/runs/7033521518/job/19141864865#step:4:51)397] (inactive timeout: 0)
debug1: forking to background
!!! MULTIPLEX SSH CONNECTION ESTABLISHED !!!
debug1: Entering interactive session.
debug1: pledge: id
OpenSSH_9.3p2, OpenSSL 3.1.3 19 Sep 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: multiplexing control connection
debug1: channel 1: new mux-control [mux-control] (inactive timeout: 0)
debug1: channel 2: new session [client-session] (inactive timeout: 0)
debug1: Sending command: rsync --server -vlogDtprze.iLsfxCIvu --inplace . sites/betterbladder1/
debug1: mux_client_request_session: master session id: 2
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
Failed to create shell
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.2.7]

**Comment by jayhill90** [comment]
Removing the STG_ENV define in my YAML file per my TSM's suggestion did not change the experienced behavior and file changes do not get deployed to wpengine.

**Comment by apmatthews** [comment]
Hey @jayhill90! It looks like you've got your build job separated from your deploy job. GitHub actions is going to run these jobs in separate containers. When the build job finishes, that container gets destroyed and a new one is created for the deploy job. As a result, the code you checkout and build in the first job (build) is not available to rsync in the second job (deploy).

Something like this should get it working for you:

```
name: Deploy to WP Engine Staging Environment
on:
  push:
    branches:
     - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Sets up node
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: gulp build
    - uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars 
        WPE_ENV: ${{secrets.STAGING_INSTALL}}
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        SCRIPT: "build.sh"
        CACHE_CLEAR: TRUE
        STG_ENV: ${{ secrets.STAGING_INSTALL}}
      env: 
        COMPOSER_AUTH: '{
          "http-basic": {
            "connect.advancedcustomfields.com": {
              "username":  ${{ secrets.ACF_KEY }},
              "password":  ${{ secrets.DOMAIN }} } } }'
        run: 'export COMPOSER_AUTH=${{ env.COMPOSER_AUTH }}'
```

If you really want to keep the job separation, GitHub Actions does provide a way to [pass artifacts between jobs](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflowhttps://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow). I haven't tried it myself, but it sounds like it could work for you.

Let us know how it goes!
