### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by M-GRV** [wpengine/github-action-wpe-site-deploy#83]
I cannot deploy currently due to this is still using node v16.

**Comment by apmatthews** [comment]
Hi @M-GRV, this action doesn't use node directly for deployment. Instead, what you are likely seeing is a deprecation warning from `actions/checkout@v3`, which does use node 16 directly. If you replace `actions/checkout@v3` for `actions/checkout@v4` in your workflow YML, the warning should disappear. We have a ticket open internally to update our documentation to reflect this change.

That said, the warning shouldn't have prevented you from deploying. If you update to `actions/checkout@v4` and your deployment still isn't working, then perhaps something else is going on. Let us know what you discover!

**Comment by M-GRV** [comment]
> Hi @M-GRV, this action doesn't use node directly for deployment. Instead, what you are likely seeing is a deprecation warning from `actions/checkout@v3`, which does use node 16 directly. If you replace `actions/checkout@v3` for `actions/checkout@v4` in your workflow YML, the warning should disappear. We have a ticket open internally to update our documentation to reflect this change.
> 
> That said, the warning shouldn't have prevented you from deploying. If you update to `actions/checkout@v4` and your deployment still isn't working, then perhaps something else is going on. Let us know what you discover!

Thank you for the fast response. I am all set!
